- name: Install prerequisites
  apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
