- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: true

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
  become: true

- name: Pull frontend Docker image
  docker_image:
    name: codeprentice/ayd2-frontend:v1
    pull: yes

- name: Run frontend container
  docker_container:
    name: frontend
    image: codeprentice/ayd2-frontend:v1
    state: started
    ports:
      - "3000:3000"
