"""value no unico en config

Revision ID: 0630995f85c2
Revises: 48c5d0446415
Create Date: 2024-09-16 23:15:12.182720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0630995f85c2'
down_revision = '48c5d0446415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_control', schema=None) as batch_op:
        batch_op.drop_constraint('config_control_value_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_control', schema=None) as batch_op:
        batch_op.create_unique_constraint('config_control_value_key', ['value'])

    # ### end Alembic commands ###
