"""Se agregaron cambios respecto al usuario

Revision ID: 8cf9a62dbfa9
Revises: 7abdf54262a0
Create Date: 2024-09-16 21:18:15.090905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf9a62dbfa9'
down_revision = '7abdf54262a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('abreviature', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abreviature'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nac', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('genero_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['fecha_nac'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.create_foreign_key(None, 'user_state', ['state_id'], ['id'])
        batch_op.create_foreign_key(None, 'gender', ['genero_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('state_id')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('genero_id')
        batch_op.drop_column('fecha_nac')

    op.drop_table('user_state')
    op.drop_table('gender')
    # ### end Alembic commands ###
