"""Agregar tabla administradores

Revision ID: ddc51461fb54
Revises: 27654e4e2d61
Create Date: 2024-10-06 22:14:21.641223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc51461fb54'
down_revision = '27654e4e2d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('ID_Administrador', sa.Integer(), nullable=False),
    sa.Column('Nombre_Completo', sa.String(length=200), nullable=False),
    sa.Column('Correo', sa.String(length=100), nullable=False),
    sa.Column('Contraseña', sa.String(length=100), nullable=False),
    sa.Column('Archivo_TextoPlano', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ID_Administrador'),
    sa.UniqueConstraint('Correo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrador')
    # ### end Alembic commands ###
