"""modificado unique constraints

Revision ID: e7685d788f3a
Revises: 8cf9a62dbfa9
Create Date: 2024-09-16 22:31:04.359491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7685d788f3a'
down_revision = '8cf9a62dbfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_fecha_nac_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_fecha_nac_key', ['fecha_nac'])

    # ### end Alembic commands ###
